name: Build JUCE Plugin (macOS)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract JUCE 8.0.7
        run: |
          curl -L https://github.com/juce-framework/JUCE/archive/refs/tags/8.0.7.zip -o juce.zip
          unzip -q juce.zip
          rm -rf JUCE
          mv JUCE-8.0.7 JUCE

      - name: Install CMake
        run: brew install cmake

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artefacts
        uses: actions/upload-artifact@v4
        with:
          name: JUCE-Build-macos
          path: |
            build/**/FM_Engine_beta.vst3/**
            build/**/FM_Engine_beta_artefacts/**
